#ifndef DBKEYS_H
#define DBKEYS_H

extern char* key_strings[];

typedef enum {
	KEY_ALIVE = 0,
	KEY_BANNER,
	KEY_SYSTEM,
	KEY_USER_RESP,
	KEY_PASS_RESP,
	KEY_PWD_RESP,
	KEY_DIFF_DATA_IP,
	KEY_FEAT_RESP,
	KEY_STAT_RESP,
	KEY_HELP_RESP,
	KEY_LAST_STATE,
	KEY_TERM_CODE,
	KEY_TERM_DESC,
	KEY_INTEREST_MASK,
	KEY_ILLEGAL_DATA,
	KEY_TOO_MUCH_DATA,
	KEY_ROBOT_DATA,
	KEY_LIST_DATA,
	KEY_TLS_CERT,
	KEY_TLS_CIPHER,
	KEY_TLS_CIPHER_VER,
	KEY_TLS_CIPHER_BITS,
	KEY_AUTH_TLS_RESP,
	KEY_LIST_RESP,
	KEY_RETR_RESP,
	KEY_INVALID_USE,
	KEY_INVALID_USE_2,
	KEY_MISC,
	KEY_ROBOT_GROUP,
	KEY_ROBOT_NOT_ALLOW,
	KEY_SYM_LINK,
	KEY_QUIT_RESP,
	KEY_PROT_RESP,
	KEY_PBSZ_RESP,
	KEY_SECURITY_TYPE,
	KEY_DATA_DBUFFER_DUMP,
	KEY_CTRL_DBUFFER_DUMP,
	KEY_TOTAL_NUM_REQ,
	KEY_EXTRA_RESP,
	KEY_OPENSSL_ERROR,
	KEY_AUTH_SSL_RESP,
	KEY_DISCONNECT_RESULT,
	KEY_DURATION,
	KEY_PASV_RESP,
	KEY_LIST_DONE,
	KEY_RETR_DONE,
	KEY_LIST_ERR_COUNT,
	KEY_PORT_RESP,
	KEY_BAD_PORT_LIST_RESP,
	KEY_BAD_PORT_LIST_DONE,
	KEY_FS_TYPE,
	KEY_SITE_RESP,
	KEY_UNCRAWLED,

	KEY_NUMBER_OF_KEYS
} db_key;



#endif
